cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
 path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
 path('cart/', views.cart, name='cart'),
 path('cart/success/', views.success, name='success'),
 path('checkout/', views.checkout, name='checkout'),
 path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
 path('hx_menu_cart/', views.hx_menu_cart, name='hx_menu_cart'),
 path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views
from django.contrib.auth.views import PasswordResetView,PasswordResetConfirmView,PasswordResetDoneView,PasswordResetCompleteView
urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('', include(('ecommerce.urls', 'ecommerce'), namespace='ecommerce')),
    path('order/', include('order.urls')),
    path('', include(('products.urls' , 'products'), namespace='products')),
    path('', include(('cart.urls' , 'cart'), namespace='cart')),
    path("__reload__/", include("django_browser_reload.urls")),


    # passwordreset
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name = 'password_reset_confirm'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.urls import path
from . import views


urlpatterns = [
 path('', views.Homepage, name='homepage'),
 path('AboutUsPage/', views.AboutUsPage, name='AboutUsPage'),
 path('contactUs/', views.contactUsView, name='contactUs'),
 path('privacy_Policy/', views.privacy_Policy, name='privacy_Policy'),
 path('meet_the_team/', views.meet_the_team, name='meet_the_team'),
 path('about_us/', views.about_us, name='about_us'),
 path('ajax_contact_form', views.ajax_contact_form, name='ajax_contact_form'),
 path('shop/', views.Shop, name='shop'),
 path('signup/', views.SignUp, name='signUp'),
 path('my_Account/', views.My_account, name='my_Account'),
 path('edit_my-account/<int:pk>/', views.edit_my_account, name='edit_my_account'),


]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from config import settings
from .cart import Cart
from products.models import Product

# Create your views here.
def add_to_cart(request, product_id):
    cart = Cart(request)
    cart.add(product_id)
    return render(request, 'cart/cart_menu_partial.html')

def cart(request):
    return render(request, 'cart/cart_item.html')

def success(request):
    return render(request, 'cart/success.html')

def update_cart(request, product_id, action):
    cart = Cart(request)

    if action == 'increment':
        cart.add(product_id, 1, True)
    else:
        cart.add(product_id, -1, True)

    product = Product.objects.get(pk=product_id)
    # item = cart.get_item(product_id)
    # if item is not None:
    #     quantity = item['quantity']
    # else:
    #     quantity = 0
    quantity = cart.get_item(product_id)

    if quantity:
        quantity= quantity['quantity']

        item = {
            'product': {
                'id': product.id,
                'name': product.name,
                'image': product.image,
                'get_thumbnail': product.get_thumbnail(),
                'price': product.price,
            },
            'total_price': (quantity * product.price)/100,
            'quantity': quantity,
        }
    else:
        item = None


    response = render(request, 'cart/cart_item_partial.html', {'item': item})
    response['HX-Trigger'] = 'update-menu-cart'

    return response

@login_required
def checkout(request):
    pub_key = settings.STRIPE_API_KEY_PUBLISHABLE
    return render(request, 'cart/checkout.html', {'pub_key': pub_key})

def hx_menu_cart(request):
    return render(request, 'cart/cart_menu_partial.html')

def hx_cart_total(request):
    return render(request, 'cart/cart_total_partial.html')

cart/templates/cart/cart_item copy.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
cart Page
{% endblock title %}



{% block css %}

{% endblock css %}

{% block content %}
<div class=" w-full">
    <div class=" w-full  mx-auto px-4">
        <h1 class="text-2xl font-semibold mb-4">Shopping Cart</h1>
        <div class="flex flex-col md:flex-row gap-4 w-full ">
            <div class="md:w-3/5">

                {% for item in cart %}
                <div id="cart-item-{{ item.product.id }}" class="bg-white rounded-lg shadow-md p-6 mb-4">
                    <table class="w-full">
                        <thead>
                            <tr>
                                <th class="text-left font-semibold">Product</th>
                                <th class="text-left font-semibold">Price</th>
                                <th class="text-left font-semibold">Quantity</th>
                                <th class="text-left font-semibold">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="py-4">
                                    <div class="flex flex-col gap-3 justify-center items-center">
                                        <img class="h-16 w-16 mr-4" src=" {{ item.product.get_thumbnail }} "
                                            alt="Product image">
                                        <div class="font-semibold"> {{item.product.name}} </div>
                                    </div>
                                </td>
                                <td class="py-4">ksh: {{ item.total_price }} /=</td>
                                <td class="py-4">
                                    <div class="flex items-center">
                                        <a class="border cursor-pointer rounded-md py-2 px-4 mr-2"
                                            hx-get=" {% url 'cart:update_cart' item.product.id 'decrement' %} "
                                            hx-target="#cart-item-{{ item.product.id }}" hx-swap='outerHTML'>
                                            -
                                        </a>
                                        <span class="text-center w-8"> {{ item.quantity }} </span>

                                        <a class="border cursor-pointer rounded-md py-2 px-4 ml-2"
                                            hx-get=" {% url 'cart:update_cart' item.product.id 'increment' %} "
                                            hx-target="#cart-item-{{ item.product.id }}" hx-swap='outerHTML'>
                                            +
                                        </a>
                                    </div>
                                </td>
                                <td class="py-4">$19.99</td>
                            </tr>
                            <!-- More product rows -->
                        </tbody>
                    </table>
                </div>
                {% endfor %}
            </div>
            <div class="md:w-2/5 flex justify-center items-center">
                <div class="bg-white rounded-lg shadow-md p-6 w-full max-w-[300px]">

                    {% include 'cart/summary.html' %}
                    <a href=" {% url 'cart:checkout' %} ">
                        <button class="bg-blue-500 text-white py-2 px-4 rounded-lg mt-4 w-full">Checkout</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}




{% block js %}

{% endblock js %}

cart/templates/cart/cart_item.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
cart Page
{% endblock title %}



{% block css %}

{% endblock css %}

{% block content %}

<!-- //////////////////////////////// -->
<div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
    <div class="products w-full md:w-3/5">
        {% for item in cart %}
        {% include 'cart/cart_item_partial.html' %}
        {% endfor %}
    </div>

    <div class="md:w-2/5 flex justify-center items-center">
        <div class="bg-white rounded-lg shadow-md p-6 w-full max-w-[300px]">

            {% include 'cart/summary_partial.html' %}
            <a href=" {% url 'cart:checkout' %} ">
                <button class="bg-blue-500 text-white py-2 px-4 rounded-lg mt-4 w-full">Checkout</button>
            </a>
        </div>
    </div>
</div>
<!-- //////////////////////////////// -->

{% endblock content %}




{% block js %}

{% endblock js %}

cart/templates/cart/cart_item_partial.html
{% if item %}
<div class="product mb-6 flex pr-6" id="cart-item-{{ item.product.id }}">
    <a href="#" class="w-1/4">
        <img class="hover:shadow-lg rounded-xl" src="{{ item.product.get_thumbnail }}">
    </a>

    <div class="w-3/4 pl-6">
        <div class="flex justify-between">

            <a href="#" class="text-lg">
                {{item.product.name }}</a>

            <span class="mb-6 pt-1 ">Ksh: {{ item.total_price }} \=</span>
        </div>

        <hr>

        <div class="quantity mt-6 flex items-center space-x-4">
            <a class="p-3 cursor-pointer bg-gray-100" hx-get="{% url 'cart:update_cart' item.product.id 'decrement' %}"
                hx-target="#cart-item-{{ item.product.id }}" hx-swap="outerHTML">
                -
            </a>
            <span>{{ item.quantity }}</span>
            <a class="p-3 cursor-pointer bg-gray-100" hx-get="{% url 'cart:update_cart' item.product.id 'increment' %}"
                hx-target="#cart-item-{{ item.product.id }}" hx-swap="outerHTML">
                +
            </a>
        </div>
    </div>
</div>

{% endif %}

cart/templates/cart/cart_menu_partial.html
<a class="flex items-center" href=" {% url 'cart:cart' %} " id="menu_add_to_cart">

    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
    </svg>
    {% if request.user.is_authenticated %}
    <span class="flex justify-center absolute -mt-5 ml-4">
        <span class=" animate-ping absolute inline-flex size-5 rounded-full bg-purple-500  opacity-75"></span>
        <span
            class="relative flex  justify-center items-center font-italic text-sm size-5 rounded-full font-bold  text-white bg-purple-500">
            {{ cart|length }}
        </span>
    </span>
    {% endif %}
</a>

cart/templates/cart/cart_total_partial.html
Ksh: {{cart.get_total_cost}}

cart/templates/cart/checkout.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
checkout Page
{% endblock title %}



{% block css %}
<link rel="stylesheet" href=" {% static 'css/card.css' %} ">
{% endblock css %}

{% block content %}

<div class=" w-full py-8">
    <div class="container mx-auto px-4">

        <!-- form start -->
        <div class="flex flex-col md:flex-row gap-4 w-full  rounded-xl">
            <div class=" md:w-3/5 flex flex-col justify-center items-center gap-4">
                <div class="max-w-[800px] ">
                    <div> {% include 'cart/shipping_information_partial.html' %}</div>


                    <div> {% include 'cart/contact_information_partial.html' %} </div>

                    <div class="mb-4 p-4 text-red-600 font-bold bg-gray-100 rounded-xl hidden" id="errors">

                    </div>

                </div>
            </div>
            <div class="md:w-2/5 flex justify-center items-center">
                <div class="bg-white rounded-lg shadow-md p-6 w-full max-w-[300px]">

                    {% include 'cart/summary_partial.html' %}

                    <button onclick="buy(event)" class="bg-blue-500 text-white py-2 px-4 rounded-lg mt-4 w-full">Confirm
                        Checkout</button>


                </div>
            </div>
        </div>
        <!-- form end -->
    </div>

</div>


{% endblock content %}




{% block js %}

<script type="application/javascript" src="https://js.stripe.com/v3/"></script>

<script>
    let element = document.getElementById('errors');
    function validateForm(data) {
        let errors = []

        if (data.first_name === '') {
            errors.push('First name is empty')
        }

        if (data.last_name === '') {
            errors.push('Last name is empty')
        }

        if (data.email === '') {
            errors.push('Email is empty')
        }

        if (data.phone === '') {
            errors.push('Phone is empty')
        }

        if (data.address === '') {
            errors.push('Address is empty')
        }

        if (data.zipcode === '') {
            errors.push('Zipcode is empty')
        }

        if (data.place === '') {
            errors.push('Place is empty')
        }
        if (errors.length > 0) {
            let html = '<ul>';
            for (let i = 0; i < errors.length; i++) {
                html += '<li>' + errors[i] + '</li>';
            }
            html += '</ul>';
            element.innerHTML = html;
            element.classList.remove('hidden'); // Remove the 'hidden' class to make the div visible
        }

        return errors
    }

    function buy(event) {
        event.preventDefault()

        let data = {
            'first_name': document.querySelector('input[name=first_name]').value,
            'last_name': document.querySelector('input[name=last_name]').value,
            'email': document.querySelector('input[name=email]').value,
            'phone': document.querySelector('input[name=phone]').value,
            'address': document.querySelector('input[name=address]').value,
            'zipcode': document.querySelector('input[name=zipcode]').value,
            'place': document.querySelector('input[name=place]').value,
        }

        let errors = validateForm(data)

        if (errors.length) {
            console.log('Errors', errors)
        } else {
            var stripe = Stripe('{{ pub_key }}')

            fetch('/order/start_order/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                credentials: 'same-origin',
                body: JSON.stringify(data)
            })
                .then(function (response) {
                    return response.json()
                })
                .then(function (session) {
                    return stripe.redirectToCheckout({ sessionId: session.session.id })
                })
                .then(function (result) {
                    if (result.error) {
                        alert(result.error.message)
                    }
                })
                .catch(function (error) {
                    console.log('Errors', error)
                })
        }

        return false
    }
</script>
{% endblock js %}

cart/templates/cart/contact_information_partial.html
<div class="flex flex-col space-y-4">
    <h1 class="text-2xl mt-6">
        CONTACT INFORMATION
    </h1>
    <div class="mt-8">
        <label for="email">Email</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="email" name="email" value="{{request.user.email}}" />
    </div>

    <div class="mt-8">
        <label for="phone">Phone</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="phone" name="phone" id="phone" placeholder="Phone" />
    </div>
</div>

cart/templates/cart/payment_information_partial.html
<div class="flex flex-col space-y-4">
    <h1 class="text-2xl mt-6">
        PAYMENT INFORMATION
    </h1>

    <div class="mt-8">
        <input class="border border-gray-300 p-4 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="email" name="" id="" placeholder="Email" />
    </div>

    <label class="mt-8 text-base leading-4 text-gray-800 dark:text-gray-50">Card details</label>
    <div class="mt-2 flex-col">
        <div>
            <input
                class="border rounded-tl rounded-tr border-gray-300 p-4 w-full text-base leading-4 placeholder-gray-600 text-gray-600"
                type="email" name="" id="" placeholder="0000 1234 6549 15151" />
        </div>
        <div class="flex-row flex">
            <input
                class="border rounded-bl border-gray-300 p-4 w-full text-base leading-4 placeholder-gray-600 text-gray-600"
                type="email" name="" id="" placeholder="MM/YY" />
            <input
                class="border rounded-br border-gray-300 p-4 w-full text-base leading-4 placeholder-gray-600 text-gray-600"
                type="email" name="" id="" placeholder="CVC" />
        </div>
    </div>

    <label class="mt-8 text-base leading-4 text-gray-800 dark:text-gray-50">Name on card</label>
    <div class="mt-2 flex-col">
        <div>
            <input
                class="border rounded border-gray-300 p-4 w-full text-base leading-4 placeholder-gray-600 text-gray-600"
                type="email" name="" id="" placeholder="Name on card" />
        </div>
    </div>

    <label class="mt-8 text-base leading-4 text-gray-800 dark:text-gray-50">Country or region</label>
    <div class="mt-2 flex-col">
        <div class="relative">
            <button id="changetext"
                class="text-left border rounded-tr rounded-tl border-gray-300 p-4 w-full text-base leading-4 placeholder-gray-600 text-gray-600 bg-white"
                type="email" name="" id="">United States</button>
            <svg onclick="showMenu(true)" id="closeIcon" class="cursor-pointer absolute top-4 right-4" width="16"
                height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M3.5 5.75L8 10.25L12.5 5.75" stroke="#27272A" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
            <svg onclick="showMenu(true)" id="openIcon"
                class="cursor-pointer hidden transform rotate-180 absolute top-4 right-4" width="16" height="16"
                viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M3.5 5.75L8 10.25L12.5 5.75" stroke="#27272A" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
            <div id="dropdown" class="mt-1 hidden absolute z-10 w-full bg-gray-50 justify-start flex-col text-gray-600">
                <div onclick="changeText('China')" class="cursor-pointer hover:bg-gray-800 hover:text-white px-4 py-2">
                    China
                </div>
                <div onclick="changeText('Russia')" class="cursor-pointer hover:bg-gray-800 hover:text-white px-4 py-2">
                    Russia</div>
                <div onclick="changeText('UK')" class="cursor-pointer hover:bg-gray-800 hover:text-white px-4 py-2">UK
                </div>
            </div>
        </div>
        <input
            class="border rounded-bl rounded-br border-gray-300 p-4 w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="text" name="" id="" placeholder="ZIP" />
    </div>

    <button
        class="mt-8 border border-transparent hover:border-gray-300 dark:bg-white dark:hover:bg-gray-900 dark:text-gray-900 dark:hover:text-white dark:border-transparent bg-gray-900 hover:bg-white text-white hover:text-gray-900 flex justify-center items-center py-4 rounded w-full">
        <div>
            <p class="text-base leading-4">Pay </p>
        </div>
    </button>

    <script>let closeIcon = document.getElementById("closeIcon");
        let openIcon = document.getElementById("openIcon");
        let dropdown = document.getElementById("dropdown");
        let text = document.getElementById("changetext");
        // more free and premium Tailwind CSS components at https://tailwinduikit.com/
        const showMenu = (flag) => {
            if (flag) {
                closeIcon.classList.toggle("hidden");
                openIcon.classList.toggle("hidden");
                dropdown.classList.toggle("hidden");
            } else {
                closeIcon.classList.toggle("hidden");
                openIcon.classList.toggle("hidden");
                dropdown.classList.toggle("hidden");
            }
        };

        const changeText = (country) => {
            text.innerHTML = country;
            closeIcon.classList.toggle("hidden");
            openIcon.classList.toggle("hidden");
            dropdown.classList.toggle("hidden");
        };
    </script>
</div>

cart/templates/cart/shipping_information_partial.html
<div class="flex flex-col space-y-4">
    <h1 class="text-2xl">
        SHIPPING INFORMATION
    </h1>
    <div class="flex flex-col md:flex-row gap-2 ">
        <div class=" w-full md:w-1/2 ">
            <label for="first_name">First name</label>
            <input
                class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
                type="text" name="first_name" value="{{request.user.first_name}}" required>
        </div>

        <div class="w-full md:w-1/2">
            <label for="last_name">Last name</label>
            <input
                class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
                type="text" name="last_name" value="{{request.user.last_name}}" required>
        </div>
    </div>
    <div class="mt-8">
        <label for="address">Address</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="address" name="address" />
    </div>
    <div class="flex flex-col md:flex-row gap-2 ">
        <div class="w-full md:w-1/2 ">
            <label for="Zip code">Zip code</label>
            <input
                class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
                type="text" id="zipcode" name="zipcode" placeholder="zipcode" required>
        </div>

        <div class="w-full md:w-1/2">
            <label for="place">City/place</label>
            <input
                class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
                type="text" id="place" name="place" placeholder="City/place" required>
        </div>
    </div>
</div>

cart/templates/cart/success.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
cart Page
{% endblock title %}



{% block css %}

{% endblock css %}

{% block content %}
<!-- component -->
<div class="min-h-[500px] flex flex-col justify-center items-center">


    <div class="relative flex flex-col sm:flex-row sm:items-center bg-white shadow rounded-md py-5 pl-6 pr-8 sm:pr-6">
        <div class="flex flex-row items-center border-b sm:border-b-0 w-full sm:w-auto pb-4 sm:pb-0">
            <div class="text-green-500">
                <svg class="w-6 sm:w-5 h-6 sm:h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
            </div>
            <div class="text-sm font-medium ml-3">Success Payment.</div>
        </div>
        <div class="text-sm tracking-wide text-gray-500 mt-4 sm:mt-0 sm:ml-4">Your Payment was Successful. You can use
            our
            services!</div>
        <div
            class="absolute sm:relative sm:top-auto sm:right-auto ml-auto right-4 top-4 text-gray-400 hover:text-gray-800 cursor-pointer">
            <a href="{% url 'ecommerce:my_Account' %}">
                <svg class="w-4 ml-4 text-red-600 animate-pulse h-4" fill="none" stroke="currentColor"
                    viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12">
                    </path>
                </svg>
            </a>
        </div>
    </div>
</div>

{% endblock content %}




{% block js %}

{% endblock js %}

cart/templates/cart/summary_partial.html
<h2 class="text-lg font-semibold mb-4">Summary</h2>
<!-- <div class="flex justify-between mb-2">
    <span>Subtotal</span>
    <span>$19.99</span>
</div>
<div class="flex justify-between mb-2">
    <span>Taxes</span>
    <span>$1.99</span>
</div>
<div class="flex justify-between mb-2">
    <span>Shipping</span>
    <span>$0.00</span>
</div> -->
<hr class="my-2">
<div class="flex justify-between mb-2">
    <span class="font-semibold">Total</span>
    <span hx-get="{%url 'cart:hx_cart_total' %}" hx-trigger="update-menu-cart from:body" hx-swap="innerHTML"
        class="font-semibold">{% include 'cart/cart_total_partial.html' %}</span>
</div>