cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
 path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
 path('cart/', views.cart, name='cart'),
 path('cart/success/', views.success, name='success'),
 path('checkout/', views.checkout, name='checkout'),
 path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
 path('hx_menu_cart/', views.hx_menu_cart, name='hx_menu_cart'),
 path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views
from django.contrib.auth.views import PasswordResetView,PasswordResetConfirmView,PasswordResetDoneView,PasswordResetCompleteView
urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('', include(('ecommerce.urls', 'ecommerce'), namespace='ecommerce')),
    path('order/', include('order.urls')),
    path('', include(('products.urls' , 'products'), namespace='products')),
    path('', include(('cart.urls' , 'cart'), namespace='cart')),
    path("__reload__/", include("django_browser_reload.urls")),


    # passwordreset
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name = 'password_reset_confirm'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.urls import path
from . import views


urlpatterns = [
 path('', views.Homepage, name='homepage'),
 path('AboutUsPage/', views.AboutUsPage, name='AboutUsPage'),
 path('contactUs/', views.contactUsView, name='contactUs'),
 path('privacy_Policy/', views.privacy_Policy, name='privacy_Policy'),
 path('meet_the_team/', views.meet_the_team, name='meet_the_team'),
 path('about_us/', views.about_us, name='about_us'),
 path('ajax_contact_form', views.ajax_contact_form, name='ajax_contact_form'),
 path('shop/', views.Shop, name='shop'),
 path('signup/', views.SignUp, name='signUp'),
 path('my_Account/', views.My_account, name='my_Account'),
 path('edit_my-account/<int:pk>/', views.edit_my_account, name='edit_my_account'),


]

products/urls.py
from django.urls import path
from . import views


urlpatterns = [
 path('product/<int:pk>/<slug:slug>/', views.Product_Page, name='product'),
]

ecommerce/models.py
# from django.contrib.auth.models import AbstractUser
# from django.db import models

# class CustomUser(AbstractUser):
#      phone_number = models.IntegerField()

ecommerce/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.mail import send_mail
from config import settings
from order.models import ContactUs

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=255, required=True)  # Change to EmailField for email validation

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use. Please use a different email address.")
        return email

    def send_welcome_email(self):
        subject = "Welcome to Ecommerce Company LMT!"
        username = self.cleaned_data['first_name']
        message = f"""
        <p>Dear {username},</p>
        <p>Welcome to Ecommerce company LMT! We're thrilled to have you join our community of savvy shoppers.</p>
        <p>At Ecommerce company LMT, we strive to provide an exceptional shopping experience, offering a wide range of
            products
            to suit your needs and preferences. Whether you're searching for the latest fashion trends, high-quality
            electronics, or
            everyday essentials, we've got you covered.</p>
        <p>As a new member, you now have access to exclusive benefits, including:</p>
        <ul>
            <li>Special discounts and promotions tailored just for you.</li>
            <li>Personalized recommendations based on your browsing and purchase history.</li>
            <li>Fast and secure checkout process for hassle-free shopping.</li>
            <li>Easy order tracking and updates on your deliveries.</li>
        </ul>
        <p>We're here to make your online shopping experience seamless and enjoyable. If you have any questions or need
            assistance,</p>
        <p>our customer support team is available to help you every step of the way.</p>
        <p>Thank you for choosing Ecommerce company LMT. We look forward to serving you and exceeding your expectations.</p>
        <p>Happy shopping!</p>
        <p>Best regards,</p>
        <p>[Ecommerce company Team]</p>
        """
        from_email = "Ecommerce company <{}>".format(settings.DEFAULT_FROM_EMAIL)  # Use the default from email
        recipient_list = [self.cleaned_data['email']]  # Use the user's email for recipient list

        send_mail(subject, message, from_email, recipient_list)

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            self.send_welcome_email()  # Send welcome email upon user creation
        return user



class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')



class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['full_name', 'email', 'phone', 'subject', 'message']

ecommerce/views.py
from django.db.models import Q
from django.contrib.auth import login
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render,redirect, get_object_or_404

from order.admin import ContactUsAdmin
from order.models import ContactUs
from .forms import SignUpForm
from django.contrib.auth.models import User

from django.db import IntegrityError

from django.contrib.auth.decorators import login_required
from products.models import Product,Category
from django.contrib import messages
from .forms import UpdateUserForm




# Create your views here.

def Homepage(request):
    products = Product.objects.all()[0:10]
    return render(request, 'ecommerce/homepage.html', {'products': products})
def AboutUsPage(request):

    return render(request, 'ecommerce/aboutUs.html')





def contactUsView(request):
    return render(request, 'ecommerce/contactUs.html')
def meet_the_team(request):
    return render(request, 'meetTheTeam.html')

def privacy_Policy(request):
    return render(request, 'privacyPolicy.html')

def about_us(request):
    return render(request, 'ecommerce/aboutUs.html')

def ajax_contact_form(request):
    if request.method == 'POST':  # Ensure that this view is accessed via a POST request
        full_name = request.POST.get('full_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        # Create a ContactUs object and save it to the database
        contact_entry = ContactUs.objects.create(
            full_name=full_name,
            email=email,
            phone=phone,
            subject=subject,
            message=message,
        )

        # Return a JSON response indicating success
        data = {
            "bool": True,
            "message": "Your message has been successfully sent!"
        }
        return JsonResponse({"data": data})
    else:
        # Return a JSON response indicating that the request method is not allowed
        return JsonResponse({"error": "Method Not Allowed"}, status=405)


def SignUp(request):

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()

    return render(request, 'registration/signup.html', {'form': form})

def Login(request):
    return render(request, 'registration/login.html')

@login_required
def My_account(request):
    return render(request, 'ecommerce/my_Account.html')



# TO BE FIXED TO BE FIXED TO BE FIXED TO BE FIXED
@login_required
def edit_my_account(request, pk):
    # Using get_object_or_404 to handle cases where user does not exist
    user = get_object_or_404(User, pk=pk)

    if request.method == 'POST':

        try:
            user = request.user
            user.first_name = request.POST.get('first_name')
            user.last_name = request.POST.get('last_name')
            user.email = request.POST.get('email')
            user.username = request.POST.get('username')
            user.save()

            messages.success(request, "User has been successfully updated")
            return redirect('/my_Account/')
        except IntegrityError:
            error_message = "Username already exists. Please choose a different username."

            return render(request, 'ecommerce/my_account_edit.html', {'user': user, 'error_message': error_message})

            # return redirect(f'/my_Account/my-account_edit/{pk}/')



    context = {
        'user': user  # using a meaningful key for the user object
    }
    return render(request, 'ecommerce/my_account_edit.html', context)
# @login_required
# def Edit_my_account(request):
    # if request.method == 'POST':
    #     user = request.user
    #     user.first_name = request.POST.get('first_name')
    #     user.last_name = request.POST.get('last_name')
    #     user.email = request.POST.get('email')
    #     user.username = request.POST.get('username')
    #     user.save()

#         # Retrieve the updated user object from the database
#         updated_user = User.objects.get(pk=user.pk)
#         print(updated_user)
#         return redirect('my_Account/')
#     return render(request, 'ecommerce/edit_my_Account.html')



@login_required
def Shop(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    active_category = request.GET.get('category', '')

    query = request.GET.get('query', '')

    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))

    if active_category:
        products = products.filter(category__slug=active_category)

    context={
        'products': products,
        'categories': categories,
        'active_category': active_category,

    }
    return render(request, 'ecommerce/shop.html', context)

ecommerce/templates/ecommerce/aboutUs.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
About Us
{% endblock title %}



{% block css %}

{% endblock css %}

{% block content %}
<div class="sm:flex items-center max-w-screen-xl">
    <div class="sm:w-1/2 p-10">
        <div class="image object-center text-center">
            <img src="https://i.imgur.com/WbQnbas.png">
        </div>
    </div>
    <div class="sm:w-1/2 p-5">
        <div class="text">
            <span class="text-gray-500 border-b-2 border-indigo-600 uppercase">About us</span>
            <h2 class="my-4 font-bold text-3xl  sm:text-4xl ">About <span class="text-indigo-600">Our Company</span>
            </h2>
            <p class="text-gray-700">
                Welcome to Faustine's Emporium! Founded with a passion for quality and style, we aim to bring you an
                exceptional
                shopping experience like no other. Our journey began with a simple idea: to curate a collection of
                handpicked products
                that reflect elegance, innovation, and craftsmanship.

                At Faustine's Emporium, we believe that every item tells a story. From timeless classics to modern
                marvels, our
                carefully curated selection encompasses a wide range of products to cater to your unique tastes and
                preferences. Whether
                you're searching for the perfect gift or treating yourself to something special, we're here to help you
                find exactly
                what you're looking for.

                We pride ourselves on providing unparalleled customer service and strive to exceed your expectations at
                every turn. With
                a dedication to excellence and a commitment to authenticity, we aim to build lasting relationships with
                our valued
                customers.

                Thank you for choosing Faustine's Emporium for your shopping needs. We look forward to serving you and
                becoming a part
                of your journey.

                Discover elegance. Explore innovation. Experience Faustine's Emporium
            </p>
        </div>
    </div>
</div>

{% endblock content %}




{% block js %}

{% endblock js %}

ecommerce/templates/ecommerce/form_edit.html
<form method="post" action="." class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
    {% csrf_token %}
    {% if error_message %}
    <div class="error-message text-center text-red-500 font-bold">
        {{ error_message }}
    </div>
    {% endif %}



    <div class="mt-8">
        <label for="first_name">first_name</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="text" name="first_name" value="{{ user.first_name}}" />
    </div>
    <div class="mt-8">
        <label for="last_name">Last_name</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="text" name="last_name" value="{{user.last_name}}" />
    </div>
    <div class="mt-8">
        <label for="username">Username</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="text" name="username" value="{{user.username}}" />
    </div>
    <div class="mt-8">
        <label for="email">Email</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="email" name="email" value="{{user.email}}" />
    </div>

    <div>
        <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-lg mt-4 w-full">Submit</button>
    </div>
</form>

ecommerce/templates/ecommerce/homeProducts.html
<!-- {% for product in products %}
<div class="w-60 h-80 bg-gray-50 p-3 flex flex-col gap-1 rounded-2xl">
    <div class="h-48 bg-gray-700 rounded-xl">
        <a href="{% url 'products:product' product.pk product.slug %}">
            <img class="w-full min-w-[200px] h-[200px] object-fit rounded-t-lg" src="{{ product.get_thumbnail }}"
                alt="product image">
        </a>
    </div>
    <div class="flex flex-col gap-4">
        <div class="flex flex-row justify-between">
            <div class="flex flex-col">
                <a href="{% url 'products:product' product.pk product.slug %}">
                    <span class="text-xl font-bold">{{product.name}}</span>
                </a>
                <p class="text-xs text-gray-700">ID: {{product.id}}</p>
            </div>
            <span class="font-bold  text-red-600">Ksh: {{product.get_display_price}}</span>
        </div>
        {% include 'add_to_cart_btn.html' %}
    </div>
</div>

{% endfor %} -->



{% for product in products %}
<div class="w-64 h-96 bg-gray-50 p-3 flex flex-col gap-1 rounded-2xl">
    <div class="h-48 bg-gray-700 rounded-xl">
        <a href="{% url 'products:product' product.pk product.slug %}">
            <img class="w-full min-w-[200px] h-[200px] object-fit rounded-t-lg" src="{{ product.get_thumbnail }}"
                alt="product image">
        </a>
    </div>
    <div class="flex flex-col gap-4 h-full ">
        <div class="h-full">
            <div class="flex flex-col justify-center h-full items-center">
                <a href="{% url 'products:product' product.pk product.slug %}">
                    <span class="text-xl font-bold">{{product.name}}</span>
                </a>

                <div class="flex justify-between w-full">
                    <p class="text-xs text-gray-700 w-full self-start">ID: {{product.id}}</p>
                    <span class="font-bold w-full  text-red-600">Ksh: {{product.get_display_price}}</span>
                </div>

            </div>

        </div>
        {% include 'add_to_cart_btn.html' %}
    </div>
</div>

{% endfor %}

<!-- {% for product in products %}
<div class="max-w-[300px] mr-6 mb-5 mx-auto">


    <div class="bg-white shadow-md rounded-lg dark:bg-gray-800 min-w-[250px] dark:border-gray-700">
        <div class="">
            <a href="{% url 'products:product' product.pk product.slug %}">
                <img class="w-full min-w-[200px] h-[200px] object-fit rounded-t-lg" src="{{ product.get_thumbnail }}"
                    alt="product image">
            </a>
        </div>
        <div class="px-5 pb-5">
            <a href="{% url 'products:product' product.pk product.slug %}">
                <h3 class="text-gray-900 font-semibold text-xl mb-3 tracking-tight dark:text-white">{{product.name}}
                </h3>
            </a>

            <div class="flex items-center mb-5 justify-between">
                <span class="text-xl font-bold text-gray-900 dark:text-white">Ksh: {{product.get_display_price}}</span>
                <span class="text-white font-bold ">
                    ID: {{product.id}}
                </span>
            </div>
            <div class="w-full flex justify-center items-center">
                {% include 'add_to_cart_btn.html' %}
            </div>
        </div>
    </div>
</div>
{% endfor %} -->

ecommerce/templates/ecommerce/homepage.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Home page
{% endblock title %}



{% block css %}

{% endblock css %}

{% block content %}
<div
    class="min-h-[500px] flex flex-col justify-center items-center bg-gradient-to-r from-indigo-800 via-transparent to-cyan-500 py-4 bg-opacity-5">

    {% if request.user.is_authenticated %}
    <div class="text-2xl">
        Hi <span class="text-2xl font-semibold">{{request.user.username }}!</span>
    </div>
    {% endif %}
    <h2 class="text-PRIMARY1 md:text-4xl text-2xl">Welcome to Tech Shop </h2>





    <div class="max-w-[500px] w-full bg-no-repeat flex flex-col justify-center items-center">
        <img src="{% static '/images/bag.png' %}" alt="shopping cart">
        <a href="{% url 'ecommerce:shop' %}">
            <button
                class=" bg-red-400 hover:bg-red-500 text-white font-bold py-3 px-6 rounded-full  hover:text-white shadow-[rgba(13,_38,_76,_0.19)_0px_9px_20px]  hover:scale-110 hover:brightness-110 animate-bounce hover:animate-none z-0 ">
                Start Shopping
            </button>
        </a>

    </div>


</div>


<div class="flex flex-wrap justify-center items-center pt-5 px-4 gap-4">
    {% include 'ecommerce/homeProducts.html' %}
</div>
{% endblock content %}




{% block js %}

{% endblock js %}

ecommerce/templates/ecommerce/iframe.html
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
    href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"
    rel="stylesheet" />

<style>
    .body {
        font-family: "Plus Jakarta Sans", sans-serif;
    }
</style>

<div class="relative w-full">
    <iframe class="w-full"
        src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d8258.043845708442!2d36.784734!3d-1.300246!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f1b1146384663%3A0xd90e0e9abcb51977!2sApplewood%20Adams!5e1!3m2!1sen!2ske!4v1689345606448!5m2!1sen!2ske"
        width="500" height="400" style="border:0;" allowfullscreen="" loading="lazy"
        referrerpolicy="no-referrer-when-downgrade">
    </iframe>
    <!-- <div class="flex flex-col items-end justify-center mt-4 md:flex-row md:justify-around md:pt-32 md:mt-0">
        <div class="relative flex-wrap hidden py-2 m-4 bg-white rounded shadow-md md:flex">
            <div class="px-6">
                <img src="https://maps.app.goo.gl/euHeNWQKPE3mMgtf9" alt="" />
                <p class="mt-1 font-medium">Applewood Adams
                    Ngong Rd, Nairobi</p>
            </div>
        </div>

    </div> -->
</div>

ecommerce/templates/ecommerce/my_Account.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
My Account
{% endblock title %}



{% block css %}

{% endblock css %}

{% block content %}
<div class=" mx-auto ">
    <div class=" flex flex-col gap-4 justify-center w-full  p-4  ">


        <h1 class=" text-2xl font-header">My Account </h1>

        <div>
            <strong>Name:</strong> {{ request.user.get_full_name }} <br>
            <strong>Username:</strong> {{ request.user.username }} <br>
            <strong>E-mail:</strong> {{ request.user.email }} <br>
            <a class="text-blue-500 underline hover:text-blue-600"
                href=" {% url 'ecommerce:edit_my_account' user.pk %} ">Edit</a>
        </div>

        <hr class="border-t-2" style="border-color: gray;">


        <h2 class="text-xl">My orders</h2>

        {% for order in request.user.orders.all %}



        <div class="w-full mb-6 p-6 flex flex-wrap bg-gray-400 rounded-xl">
            <div class="mb-4 flex justify justify-between">
                <a href="#">Order id: {{order.id}}</a>
            </div>

            <div class="mb-6 w-full">

                {% for item in order.items.all %}

                <div class="mb-4 flex pr-4">
                    <a href="{% url 'products:product' item.product.pk item.product.slug %}" class="w-1/4">
                        <img class="rounded-xl" src=" {{item.product.get_thumbnail}} " alt="product image">
                    </a>

                    <div class="w-3/4 pl-4">
                        <div class="flex justify-between">
                            <a
                                href="{% url 'products:product' item.product.pk item.product.slug %}">{{item.product.name}}</a>

                            <p class="mb-6 pt-1 ">Ksh: {{item.get_total_price }} </p>

                        </div>

                        <hr class="border-t-2" style="border-color: gray;">

                        <div class="mt-6">
                            Quantity: {{item.quantity}}
                        </div>

                    </div>

                </div>
                {% endfor %}
            </div>

            <div>
                <p class="text-lg">Date: {{order.created_at }}</p>
                <p class="text-lg">Total: Ksh: {{ order.get_total_price }} </p>

            </div>

        </div>
        {% endfor %}

    </div>
</div>
{% endblock content %}




{% block js %}

{% endblock js %}

ecommerce/templates/ecommerce/my_account_edit.html
{% extends 'base.html' %}
{% load static %}
{% load tailwind_filters %}

{% block title %}
My Account edit
{% endblock title %}



{% block css %}

{% endblock css %}

{% block content %}
<form method="post" action="." class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
    {% csrf_token %}
    {% if error_message %}
    <div class="error-message text-center text-red-500 font-bold">
        {{ error_message }}
    </div>
    {% endif %}



    <div class="mt-8">
        <label for="first_name">first_name</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="text" name="first_name" value="{{ user.first_name}}" />
    </div>
    <div class="mt-8">
        <label for="last_name">Last_name</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="text" name="last_name" value="{{user.last_name}}" />
    </div>
    <div class="mt-8">
        <label for="username">Username</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="text" name="username" value="{{user.username}}" />
    </div>
    <div class="mt-8">
        <label for="email">Email</label>
        <input class="border border-gray-300 p-3 rounded w-full text-base leading-4 placeholder-gray-600 text-gray-600"
            type="email" name="email" value="{{user.email}}" />
    </div>

    <div>
        <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-lg mt-4 w-full">Submit</button>
    </div>
</form>
{% endblock content %}




{% block js %}

{% endblock js %}

ecommerce/templates/ecommerce/shop.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Shopping Page
{% endblock title %}



{% block css %}

{% endblock css %}

{% block content %}

<div class=" mx-auto flex flex-wrap   ">
    <div class="filter w-full lg:w-1/6  p-4 pr-0  ">
        <h1 class=" text-2xl font-header">Sidebar</h1>
        <div class="flex  w-full">
            <form class=" w-full max-w-[330px]" method="get" action=".">
                <label class="mb-2 text-sm font-medium text-gray-900 sr-only" for="default-search">Search</label>
                <div class="relative">
                    <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                        <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"
                            class="w-4 h-4  ">
                            <path d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" stroke-width="2"
                                stroke-linejoin="round" stroke-linecap="round" stroke="currentColor"></path>
                        </svg>
                    </div>
                    <input name="query" placeholder="Search ..."
                        class="block w-full p-2 py-2 ps-10 text-lg text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 outline-none focus:border-blue-500 dark:bg-gray-400 dark:border-gray-400 dark:placeholder-gray-900 dark:text-black dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        id="default-search" type="search" />
                    <button
                        class="absolute end-2.5 bottom-1/2 translate-y-1/2 p-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"
                            class="w-4 h-4">
                            <path d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" stroke-width="2"
                                stroke-linejoin="round" stroke-linecap="round" stroke="currentColor"></path>
                        </svg>
                        <span class="sr-only">Search</span>
                    </button>
                </div>
            </form>

        </div>

        <h1 class=" text-2xl font-header mt-4">Categories</h1>

        <ul class="space-y-2">
            <li><a href=" {% url 'ecommerce:shop' %} "
                    class=" {% if not active_category %}text-purple-600 {% else %}text-gray-600 {% endif %} ">All
                    categories</a></li>

            {% for category in categories %}
            <li><a href=" {% url 'ecommerce:shop'%}?category={{category.slug}} "
                    class=" {% if category.slug == active_category %}text-purple-600 {% else %}text-gray-600 {% endif %} ">
                    {{category.name}} </a></li>
            {% endfor %}

        </ul>


    </div>

    <div class=" w-full lg:w-5/6 px-4 flex justify-center items-center">
        <div class="flex flex-wrap gap-4 justify-center items-center">

            {% include 'ecommerce/homeProducts.html' %}
        </div>
    </div>

</div>
{% endblock content %}




{% block js %}

{% endblock js %}