cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
 path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
 path('cart/', views.cart, name='cart'),
 path('cart/success/', views.success, name='success'),
 path('checkout/', views.checkout, name='checkout'),
 path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
 path('hx_menu_cart/', views.hx_menu_cart, name='hx_menu_cart'),
 path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views
from django.contrib.auth.views import PasswordResetView,PasswordResetConfirmView,PasswordResetDoneView,PasswordResetCompleteView
urlpatterns = [
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('', include(('ecommerce.urls', 'ecommerce'), namespace='ecommerce')),
    path('order/', include('order.urls')),
    path('', include(('products.urls' , 'products'), namespace='products')),
    path('', include(('cart.urls' , 'cart'), namespace='cart')),
    path("__reload__/", include("django_browser_reload.urls")),


    # passwordreset
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name = 'password_reset_confirm'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.urls import path
from . import views


urlpatterns = [
 path('', views.Homepage, name='homepage'),
 path('AboutUsPage/', views.AboutUsPage, name='AboutUsPage'),
 path('contactUs/', views.contactUsView, name='contactUs'),
 path('privacy_Policy/', views.privacy_Policy, name='privacy_Policy'),
 path('meet_the_team/', views.meet_the_team, name='meet_the_team'),
 path('about_us/', views.about_us, name='about_us'),
 path('ajax_contact_form', views.ajax_contact_form, name='ajax_contact_form'),
 path('shop/', views.Shop, name='shop'),
 path('signup/', views.SignUp, name='signUp'),
 path('my_Account/', views.My_account, name='my_Account'),
 path('edit_my-account/<int:pk>/', views.edit_my_account, name='edit_my_account'),


]

templates/add_to_cart_btn.html
<a class="w-full" href="#" hx-get="{% url 'cart:add_to_cart' product.id %}" hx-target="#menu_add_to_cart"
    hx-swap="outerHTML">

    <div class="w-full">

        <button class="hover:bg-sky-700 text-gray-50 bg-sky-800 py-2 rounded-md w-full p-6">Add
            to cart
        </button>
    </div>
</a>

templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- New link tag for the SVG favicon -->
    <link rel="icon"
        href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' class='h-6 w-6' fill='none' viewBox='0 0 24 24' stroke='%23bce1ff' stroke-width='3'%3E%3Cpath stroke-linecap='round' stroke-linejoin='round' d='M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z' /%3E%3C/svg%3E"
        type="image/svg+xml">



    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->

    {% tailwind_css %}

    <title>
        {% block title %}

        {% endblock title %} | OnlineShop
    </title>

    {% block css %}

    {% endblock css %}

</head>
<body class="bg-gradient-to-r from-gray-100 via-[#bce1ff] to-gray-100  ">
    {% include 'navbar.html' %}
    <section class="bg-animated-bg">


        <!-- ::::::::::::::::::::::::::::::::::::: -->
        <!-- ::::::::::::::::::::::::::::::::::::: -->

        <!-- sm:px-6 lg:px-8 -->
        <section
            class="mt-[60px] max-w-screen-2xl py-4 mx-auto  bg-slate-400 bg-opacity-10 border-r border-l border-gray-300"
            style="background-image: url('https://ecomerce-bucket-2.s3.eu-north-1.amazonaws.com/images/bg9.svg');">
            {% block content %}

            {% endblock content %}
        </section>
        <!-- ::::::::::::::::::::::::::::::::::::: -->
        <!-- ::::::::::::::::::::::::::::::::::::: -->


        {% include 'footer.html' %}





    </section>
    <!-- ::::::::::::::::::::::::::::::::::::: -->
    {% block js %}

    {% endblock js %}
    <!-- ::::::::::::::::::::::::::::::::::::: -->

    <script src="{% static 'js/navbar.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/htmx/1.9.10/htmx.min.js"></script>

    <!-- <script src="https://unpkg.com/htmx.org@1.7.0"></script> -->


</body>
</html>

templates/footer.html
<!-- component -->
<footer class="  ">
    <div
        class=" bg-gradient-to-r from-gray-100 via-[#bce1ff] to-gray-100  max-w-screen-2xl px-4 py-16 mx-auto sm:px-6 lg:px-8 border-r border-l border-gray-300 ">
        <div class="grid grid-cols-1 gap-8 lg:grid-cols-3">
            <div>
                <a href="/" class="flex items-center gap-2 text-gray-700 hover:text-gray-900">
                    <svg class="h-6 w-6 flex-shrink-0 text-gray-900 group-hover:text-gray-500" fill="none"
                        viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
                    </svg>
                    <span class="font-bold">Ecommerce</span>
                </a>
                <p class="max-w-xs mt-4 text-sm text-gray-600">
                    Copyright © Faustine's Emporium 2024. All rights reserved. Crafted with care by Faustine. Reach out:
                    mwendwafaustine2@gmail.com
                </p>
                <div class="flex mt-8 space-x-6 text-gray-600">
                    <a class="hover:opacity-75" href target="_blank" rel="noreferrer">
                        <span class="sr-only"> Facebook </span>
                        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                            <path fillRule="evenodd"
                                d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                                clipRule="evenodd" />
                        </svg>
                    </a>
                    <a class="hover:opacity-75" href target="_blank" rel="noreferrer">
                        <span class="sr-only"> Instagram </span>
                        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                            <path fillRule="evenodd"
                                d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z"
                                clipRule="evenodd" />
                        </svg>
                    </a>
                    <a class="hover:opacity-75" href target="_blank" rel="noreferrer">
                        <span class="sr-only"> Twitter </span>
                        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                            <path
                                d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
                        </svg>
                    </a>
                    <a class="hover:opacity-75" href target="_blank" rel="noreferrer">
                        <span class="sr-only"> GitHub </span>
                        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                            <path fillRule="evenodd"
                                d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                                clipRule="evenodd" />
                        </svg>
                    </a>
                    <a class="hover:opacity-75" href target="_blank" rel="noreferrer">
                        <span class="sr-only"> Dribbble </span>
                        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                            <path fillRule="evenodd"
                                d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z"
                                clipRule="evenodd" />
                        </svg>
                    </a>
                </div>
            </div>
            <div class="grid grid-cols-1 gap-8 lg:col-span-2 sm:grid-cols-2 lg:grid-cols-4">
                <div>
                    <p class="font-medium">
                        Company
                    </p>
                    <nav class="flex flex-col mt-4 space-y-2 text-sm text-gray-500">
                        <a href="{% url 'ecommerce:about_us' %}" class="hover:opacity-75" href> About </a>
                        <a href="{% url 'ecommerce:meet_the_team' %}" class="hover:opacity-75" href> Meet the Team </a>

                    </nav>
                </div>
                <!-- <div>
                    <p class="font-medium">
                        Services
                    </p>
                    <nav class="flex flex-col mt-4 space-y-2 text-sm text-gray-500">
                        <a class="hover:opacity-75" href> 1on1 Coaching </a>
                        <a class="hover:opacity-75" href> Company Review </a>
                        <a class="hover:opacity-75" href> Accounts Review </a>
                        <a class="hover:opacity-75" href> HR Consulting </a>
                        <a class="hover:opacity-75" href> SEO Optimisation </a>
                    </nav>
                </div> -->
                <div>
                    <p class="font-medium">
                        Helpful Links
                    </p>
                    <nav class="flex flex-col mt-4 space-y-2 text-sm text-gray-500">
                        <a href="{% url 'ecommerce:contactUs' %}" class="hover:opacity-75"> Contact </a>
                        <!-- <a class="hover:opacity-75" href> FAQs </a>
                        <a class="hover:opacity-75" href> Live Chat </a> -->
                    </nav>
                </div>
                <div>
                    <p class="font-medium">
                        Legal
                    </p>
                    <nav class="flex flex-col mt-4 space-y-2 text-sm text-gray-500">
                        <a href="{% url 'ecommerce:privacy_Policy' %}" class="hover:opacity-75" href> Privacy Policy
                        </a>
                        <!-- <a class="hover:opacity-75" href> Terms &amp; Conditions </a>
                        <a class="hover:opacity-75" href> Returns Policy </a>
                        <a class="hover:opacity-75" href> Accessibility </a> -->
                    </nav>
                </div>
            </div>
        </div>
        <p class="mt-8 text-xs text-gray-800">
            © 2024 Ecommerce
        </p>
        <p class="mt-6 ">Designed and developed by <a class="text-blue-600 underline italic"
                href="https://kilundi.onrender.com/#about" target="_blank">@Faustinemwendwa</a></p>
    </div>
</footer>

templates/navbar.html
<header class="text-gray-700 body-font ">
    <nav class=" fixed top-0 left-0 right-0 border-b-2 bg-[#bce1ff] shadow-[0_35px_60px_-15px_rgba(0,0,0,0.3)] z-50 ">
        <div class="max-w-screen-2xl  mx-auto px-4  ">
            <div class="flex justify-between">

                <div class="flex space-x-4">
                    <!-- logo -->
                    <div>
                        <a href="/" class="flex items-center gap-2 py-5 text-gray-700 hover:text-gray-900">
                            <svg class="h-6 w-6 flex-shrink-0 text-gray-900 group-hover:text-gray-500" fill="none"
                                viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
                            </svg>
                            <span class="font-bold">Ecommerce</span>
                        </a>
                    </div>

                </div>


                <!-- primary nav -->
                <div class="hidden md:flex items-center space-x-1 font-bold">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'ecommerce:shop' %}"
                        class="block w-full py-2 px-4 rounded-xl text-sm hover:bg-gray-200">Shop</a>
                    {% endif %}
                    <a href=" {% url 'ecommerce:AboutUsPage' %}  "
                        class="block w-full py-2 px-4 text-sm hover:bg-gray-200 rounded-xl">About</a>
                    <a href=" {% url 'ecommerce:contactUs' %} "
                        class="block w-full py-2 px-4 text-sm hover:bg-gray-200 rounded-xl">Contact</a>


                </div>

                <div class="flex gap-4 items-center justify-center">


                    <!-- /////////////////////// -->
                    <div hx-get="{%url 'cart:hx_menu_cart' %}" hx-trigger="update-menu-cart from:body"
                        hx-swap="innerHTML">

                        {% include 'cart/cart_menu_partial.html' %}
                    </div>

                    <!-- /////////////////////// -->

                    <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown" type="button">

                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 " fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">

                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </button>

                    <!-- Dropdown menu -->
                    <div id="dropdown"
                        class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                        <ul class="py-2 text-sm text-gray-700 dark:text-gray-200"
                            aria-labelledby="dropdownDefaultButton">
                            {% if not request.user.is_authenticated %}
                            <li>
                                <a href=" {% url 'ecommerce:signUp' %} " class="block px-4 py-2">SignUp</a>
                            </li>
                            <li>
                                <a href="{% url 'login' %}"
                                    class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Login</a>
                            </li>
                            {% endif %}

                            {% if request.user.is_authenticated %}

                            <li>
                                <a href=" {% url 'ecommerce:my_Account' %} "
                                    class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">My
                                    Account</a>
                            </li>
                            <!-- <li>
                                <a href="#"
                                    class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Favorates</a>
                            </li> -->
                            <li>
                                <div
                                    class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                                    <form method="post" action="{% url 'logout' %}">
                                        {% csrf_token %}

                                        <button class=" font-bold w-full text-start" type="submit">Logout</button>
                                    </form>
                                </div>
                            </li>
                            {% endif %}
                        </ul>
                    </div>




                    <!-- mobile button goes here -->
                    <div class="md:hidden flex items-center">
                        <button class="mobile-menu-button">
                            <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M4 6h16M4 12h16M4 18h16" />
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!-- mobile menu -->
        <div class="mobile-menu hidden md:hidden bg-animated-bg ">
            <div class="flex justify-center items-center flex-col p-4 text-center gap-2">
                <div class="w-full flex flex-col justify-center items-center gap-2">
                    {% if request.user.is_authenticated %}

                    <a href="{% url 'ecommerce:shop' %}" class="block w-full  text-sm ">
                        <div
                            class="flex   bg-slate-300 p-3 cursor-pointer rounded-xl justify-start items-center hover:text-SECONDARY1 hover:bg-slate-500 font-bold">
                            shop

                        </div>
                    </a>
                    {% endif %}

                    <a href="{% url 'ecommerce:AboutUsPage' %}" class="block w-full  text-sm ">
                        <div
                            class="flex   bg-slate-300 p-3 cursor-pointer rounded-xl justify-start items-center hover:text-SECONDARY1 hover:bg-slate-500 font-bold">
                            About

                        </div>
                    </a>



                    </a>
                    <a href="{% url 'ecommerce:contactUs' %}" class="block w-full  text-sm ">
                        <div
                            class="flex   bg-slate-300 p-3 cursor-pointer rounded-xl justify-start items-center hover:text-SECONDARY1 hover:bg-slate-500 font-bold">
                            Contact

                        </div>
                    </a>

                </div>
            </div>
    </nav>
</header>

templates/privacyPolicy.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Privacy policy
{% endblock title %}



{% block css %}

{% endblock css %}

{% block content %}


<div class="">
    <div class="container mx-auto px-4 py-8">
        <h1 class="text-3xl font-bold mb-4">Privacy Policy</h1>

        <p class="mb-4">
            This privacy policy sets out how our website uses and protects any information that you give us when you use
            this
            website.
        </p>

        <h2 class="text-2xl font-bold mb-2">Information We Collect</h2>

        <p class="mb-4">
            We may collect the following information:
        </p>

        <ul class="list-disc list-inside mb-4">
            <li>Your name and contact information</li>
            <li>Demographic information</li>
            <li>Other information relevant to customer surveys and/or offers</li>
        </ul>

        <h2 class="text-2xl font-bold mb-2">How We Use the Information</h2>

        <p class="mb-4">
            We require this information to understand your needs and provide you with a better service, and in
            particular
            for
            the following reasons:
        </p>

        <ul class="list-disc list-inside mb-4">
            <li>Internal record keeping</li>
            <li>Improving our products and services</li>
            <li>Sending promotional emails about new products, special offers, or other information which we think you
                may
                find
                interesting</li>
            <li>From time to time, we may also use your information to contact you for market research purposes. We may
                contact
                you by email, phone, or mail. We may use the information to customize the website according to your
                interests.</li>
        </ul>

        <h2 class="text-2xl font-bold mb-2">Security</h2>

        <p class="mb-4">
            We are committed to ensuring that your information is secure. In order to prevent unauthorized access or
            disclosure,
            we have put in place suitable physical, electronic, and managerial procedures to safeguard and secure the
            information we collect online.
        </p>

        <h2 class="text-2xl font-bold mb-2">Cookies</h2>

        <p class="mb-4">
            A cookie is a small file that asks permission to be placed on your computer's hard drive. Once you agree,
            the
            file
            is added, and the cookie helps analyze web traffic or lets you know when you visit a particular site.
            Cookies
            allow
            web applications to respond to you as an individual. The web application can tailor its operations to your
            needs,
            likes, and dislikes by gathering and remembering information about your preferences.
        </p>

        <p class="mb-4">
            Overall, cookies help us provide you with a better website by enabling us to monitor which pages you find
            useful
            and which you do not. A cookie in no way gives us access to your computer or any information about you,
            other
            than
            the data you choose to share with us.
        </p>

        <h2 class="text-2xl font-bold mb-2">Links to Other Websites</h2>

        <p class="mb-4">
            Our website may contain links to other websites of interest. However, once you have used these links to
            leave
            our
            site, you should note that we do not have any control over that other website. Therefore, we cannot be
            responsible
            for the protection and privacy of any information which you provide whilst visiting such sites and such
            sites
            are
            not governed by this privacy statement. You should exercise caution and look at the privacy statement
            applicable
            to
            the website in question.
        </p>

        <h2 class="text-2xl font-bold mb-2">Controlling Your Personal Information</h2>

        <p class="mb-4">
            You may choose to restrict the collection or use of your personal information in the following ways:
        </p>

        <ul class="list-disc list-inside mb-4">
            <li>If you have previously agreed to us using your personal information for direct marketing purposes, you
                may
                change your mind at any time by writing to or emailing us at [email protected]</li>
            <li>We will not sell, distribute, or lease your personal information to third parties unless we have your
                permission
                or are required by law to do so. We may use your personal information to send you promotional
                information
                about
                third parties which we think you may find interesting if you tell us that you wish this to happen.</li>
            <li>You may request details of personal information which we hold about you. If you would like a copy of the
                information held on you, please write to [Your Company Name, Address, City, State, Zip Code] or email
                [email protected]</li>
            <li>If you believe that any information we are holding on you is incorrect or incomplete, please write to or
                email
                us as soon as possible at the above address. We will promptly correct any information found to be
                incorrect.
            </li>
        </ul>

        <p class="mb-4">
            This privacy policy is subject to change without notice.
        </p>
    </div>
</div>

{% endblock content %}




{% block js %}

{% endblock js %}